[[
	{
		u'status': u'ownedBlue', 
		u'layer': 3, 
		u'endTime': 78.0, 
		u'startTime': 13.0, 
		u'didSucceed': True
	}, {
		u'status': u'balanced', 
		u'layer': 0, 
		u'endTime': 87.0, 
		u'startTime': 49.0, 
		u'didSucceed': False
	}, {
		u'status': u'balanced', 
		u'layer': 2, 
		u'endTime': 57.0, 
		u'startTime': 28.0, 
		u'didSucceed': True
	}, {
		u'status': u'ownedBlue', 
		u'layer': 2, 
		u'endTime': 97.0, 
		u'startTime': 25.0, 
		u'didSucceed': False
	}, {
		u'status': u'ownedBlue', 
		u'layer': 1, 
		u'endTime': 92.0, 
		u'startTime': 24.0, 
		u'didSucceed': True
	}, {
		u'status': u'ownedRed', 
		u'layer': 2, 
		u'endTime': 98.0, 
		u'startTime': 11.0, 
		u'didSucceed': False
	}, {
		u'status': u'balanced', 
		u'layer': 4, 
		u'endTime': 70.0, 
		u'startTime': 45.0, 
		u'didSucceed': False
	}, {
		u'status': u'ownedRed', 
		u'layer': 0, 
		u'endTime': 61.0, 
		u'startTime': 1.0, 
		u'didSucceed': False
		}, {
		u'status': u'balanced', 
		u'layer': 3, 
		u'endTime': 59.0, 
		u'startTime': 30.0, 
		u'didSucceed': True
		}], [{
		u'status': u'ownedBlue', 
		u'layer': 3, 
		u'endTime': 78.0, 
		u'startTime': 13.0, 
		u'didSucceed': True}, {u'status': u'balanced', u'layer': 0, u'endTime': 87.0, u'startTime': 49.0, u'didSucceed': False}, {u'status': u'balanced', u'layer': 2, u'endTime': 57.0, u'startTime': 28.0, u'didSucceed': True}, {u'status': u'ownedBlue', u'layer': 2, u'endTime': 97.0, u'startTime': 25.0, u'didSucceed': False}, {u'status': u'ownedBlue', u'layer': 1, u'endTime': 92.0, u'startTime': 24.0, u'didSucceed': True}, {u'status': u'ownedRed', u'layer': 2, u'endTime': 98.0, u'startTime': 11.0, u'didSucceed': False}, {u'status': u'balanced', u'layer': 4, u'endTime': 70.0, u'startTime': 45.0, u'didSucceed': False}, {u'status': u'ownedRed', u'layer': 0, u'endTime': 61.0, u'startTime': 1.0, u'didSucceed': False}, {u'status': u'balanced', u'layer': 3, u'endTime': 59.0, u'startTime': 30.0, u'didSucceed': True}]]